pool:
  vmImage: 'ubuntu-latest'

trigger:
  batch: true
  branches:
    include:
    - master

pr: none

steps:
- task: CopyFiles@2
  inputs:
    Contents: |
      public/**/*
      src/**/*
      package.json
      package-lock.json
      vue.config.js
      nginx.conf
      .eslintrc*
      .dockerignore
      tsconfig.json
      Dockerfile
    TargetFolder: '$(Build.StagingDirectory)/'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.StagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'